### ISSUE TITLE
Finish jekyll install

### ISSUE THREAD

**Issue by carodew** [GSA/10x#13]
## it should include …
- [x] @jeremyzilar takes a machete to the extraneous files we don't need
- [x] pull in the more recent changes from master
- [x] then will submit a PR to master

## it's done when …
- [x] jekyll 
- [x] is on master
- [x] and is on ~federalist~ 
- [x] ~initial scan from W Slack~ _I am not sure this needs to happen yet. This can come later after we have a working prototype_

**Comment by carodew** [comment]
Notes from chatting with @jeremyzilar -
- started working on it, realized we needed to work on our content before he moves forward 
- not sure where it left off
- `bundle exec jekyll serve` to run locally and in the context of your bundled gems

**Comment by jeremyzilar** [comment]
Here is the PR for this issue: https://github.com/GSA/10x/pull/41

**Comment by carodew** [comment]
![image](https://user-images.githubusercontent.com/10144074/36500290-ec4f3b1c-1711-11e8-9e72-54e22dc271db.png)
