### ISSUE TITLE
visual bug: submit button layout wonkiness

### ISSUE THREAD

**Issue by carodew** [GSA/10x#134]
On display here: https://demo.10x.gsa.gov/
and here: https://demo.10x.gsa.gov/send-us-an-idea/

The submit button spans the full width of the layout, which is correct for mobile, but desktop it should be aligned horizontally with the related content. Something is afoot!

**Comment by thisisdano** [comment]
On this now

**Comment by carodew** [comment]
Awesome! Feel free to merge to demo when you're done but I want at least one other 10x person to review the demo site before merging to master (I also made a lot of copy changes). Thanks again!
