### ISSUE TITLE
Write a quick 'getting started' guide and add it to the readme 

### ISSUE THREAD

**Issue by carodew** [GSA/10x#14]
## it should …
- [x] include very simple, all inclusive (aka starting from scratch) step-by-step instructions on how to run the site locally
- [x] follow (relevant) best practices described in https://open-source-guide.18f.gov/making-readmes-readable/ 

## it's done when …
- [x] instructions are added to the Readme. 
- [x] Carolyn is able to remember how to do it after a week or so away from the project, which is a pretty good approximation for someone starting from scratch.

**Comment by carodew** [comment]
One step is going to be this to run the site locally – 

`bundle exec jekyll serve` to run locally and in the context of your bundled gems

**Comment by carodew** [comment]
@thisisdano to fill out details to this card.

**Comment by thisisdano** [comment]
https://github.com/GSA/10x/issues/20 might have addressed this issue? 
@carodew give it a look and maybe try and follow the instructions?

**Comment by carodew** [comment]
How about we ask @thebestsophist to test it instead, given that she already has to go through the process anyway?
