### ISSUE TITLE
code the thing

### ISSUE THREAD

**Issue by carodew** [GSA/10x#36]
## it should include …
- [ ] thing
- [ ] and another thing

## it's done when …
- [ ] thing
- [ ] and another thing

## phases 
- [ ] content
- [ ] wireframing/iA
- [ ] give it a look and feel 
- [ ] translate into code
- [ ] testing
- [ ] push to live site
- [ ] rapid validation / usability testing

**Comment by thisisdano** [comment]
Maybe close this, as `Code the thing` and `Design the thing` will be the same thing in my workflow?

**Comment by carodew** [comment]
works for me!
