### ISSUE TITLE
mood boards and methodological approach to visual style 

### ISSUE THREAD

**Issue by carodew** [GSA/10x#38]
## it should include …
- [x] At least two collections of [mood boards](https://www.lullabot.com/articles/why-web-designers-should-moodboard) / [style tiles](http://styletil.es/) in Invision or elsewhere
- [x] These should collect colors, type, images, and combinations that suggest a tone and visual direction

## it's done when …
- [x] We've discussed these deliverables with our project stakeholders
- [x] Iterated on the deliverables if necessary
- [x] Agreed/decided on a direction

**Comment by thisisdano** [comment]
Starting work on these here: https://gsa.invisionapp.com/boards/2S3JM23NHX3/

**Comment by thisisdano** [comment]
Another one!
https://gsa.invisionapp.com/boards/SW3KETAAKGE/

**Comment by thisisdano** [comment]
We're headed to the frontier!
