### ISSUE TITLE
Create a simple splash page to point URL to

### ISSUE THREAD

**Issue by carodew** [GSA/10x#43]
need this for #9

## it should include …
- [x] 10x blurb
- [x] something about this coming soon, but not like in a lame way
- [x] contact information 10x@gsa.gov

## it's done when …
- [x] it's on master and you can view it via https://federalist-proxy.app.cloud.gov/site/gsa/10x/

**Comment by carodew** [comment]
@willcahoe does the content list look right to you?

**Comment by willcahoe** [comment]
@carodew looks good, maybe give people something to chew on while they wait for the live site - like a link to the annual report or something?

**Comment by carodew** [comment]
Yeah, that's a good idea! I added that and also a link to the slick sheet.

**Comment by thisisdano** [comment]
The work I did for https://github.com/GSA/10x/issues/20 will hopefully move us along toward this issue as well. It should be up on `master` soon.

**Comment by carodew** [comment]
@thisisdano I'd like for us to be able to push the version that includes the email address to production (not just demo) before we close this issue – how soon can that happen?

**Comment by thisisdano** [comment]
I'll push this to master right now

**Comment by thisisdano** [comment]
ok, done, should be there as soon as federalist rebuilds
