### ISSUE TITLE
Set up a staging/demo site

### ISSUE THREAD

**Issue by carodew** [GSA/10x#44]
## it should include …
- [x] a new branch that is named so that it's obviously the staging site
- [x] the demo/staging branch is the default branch for merging PRs
- [x] the master branch is set up as a protected branch
- [x] that branch is set up as the demo branch in Federalist

## it's done when …
- [x] opening a PR automatically populates the demo branch as the merge-to branch
- [x] the master branch is set as protected
- [x] we have a working URL for both the live site and the demo branch (via Federalist) and those URLs is included on the front page of this GitHub repo (most typically these are located in the repo description, near the top of the code tab, but could be included in the readme or other appropriate place).

**Comment by thisisdano** [comment]
Set `demo` as the default branch

**Comment by thisisdano** [comment]
Assigned `demo` as the demo site branch in Federalist

**Comment by thisisdano** [comment]
This could possibly be closed. All this stuff is done even though we haven't yet pointed the Federalist previews to non-Federalist URLs.

**Comment by carodew** [comment]
I think the non-Federalist URLs bit can be considered part of registering the subdomain. 

I only took a cursory glance at the main GitHub page and my only thought is that the Federalist URL is so long it's truncated in the description box. The link works fine, but I wonder if we should just add the main URL and the demo URL to the readme also, in case people would rather copy/paste?

**Comment by carodew** [comment]
Picking this up to add the links to the Readme so we can close it out.
