### ISSUE TITLE
Onboard Cordelia

### ISSUE THREAD

**Issue by carodew** [GSA/10x#47]
## this should include …

- [x] @thebestsophist added to the GitHub repo as a collaborator - @willcahoe 
- [x] she's able to get the local install up and running - @thebestsophist
- [x] invited to all the website team meetings - @willcahoe 
- [x] update her on where the content is right now - @willcahoe and @carodew
- [x] walk her through the framing docs created so far - @carodew probably
- [x] add to Team Drive in Google Drive

## it's done when 
- [x] @thebestsophist agrees it's done

**Comment by carodew** [comment]
@willcahoe we also need to add her to the Google Team Drive for 10x. I'm adding it to the above.

**Comment by thebestsophist** [comment]
all good!

**Comment by carodew** [comment]
Done! 🎉
