### ISSUE TITLE
Write the "I'm pitching an idea" content

### ISSUE THREAD

**Issue by carodew** [GSA/10x#51]
## it should include …

- [ ] how to submit an idea
- [ ] information about expected phase durations, timelines from previous projects
- [ ] information about what kind of commitment/role we expect from submitters
- [ ] call for ideas schedule
- [ ] how to message the team 

## it's done when …
- [ ] the team has agreed upon the content and there are no more comments/suggestions in the doc

**Comment by willcahoe** [comment]
Updated the definition of done to include:

- [ ] the content is ready to be used in wireframes/mock ups

**Comment by willcahoe** [comment]
## it should include …

- [ ] how to submit an idea
- [ ] information about expected phase durations, timelines from previous projects
- [ ] information about what kind of commitment/role we expect from submitters
- [ ] call for ideas schedule
- [ ] how to message the team

## How to submit an idea

If you are ready to submit your idea, simply email us at 10x@gsa.gov with your pitch title in the subject line. Remember, your pitch should be no more than two to three sentences.


## Expected phase durations

Phase 1 projects are designed to last about two weeks, but we can be flexible and adjust the timetable for your project as needed. All phase 1 projects must be completed by the end of the Fiscal Year in which they were awarded funding. For information on subsequent funding phase durations, check out our [overview page](10x overview).



## What kind of commitment/role we expect from submitters

As a pitch author, you will serve in an advisory role as a subject matter expert. 10x will match your project with an in-house technologist at GSA who will conduct investigation research on your behalf. You will be expected to coordinate and work closely with your TTS Sponsor and the person or team that executes phase 1 of the project; however, your involvement is ultimately up to you and your availability.


## Call for ideas schedule

Our next open season for submitting pitches will begin around mid-May and end in early June. We will update our site with a final schedule as soon as we hammer out the details.

# How to message the team

Contact Us -> Have a question or a problem? Get in touch.
