### ISSUE TITLE
Write/gather/edit content for the overview of 10x

### ISSUE THREAD

**Issue by carodew** [GSA/10x#52]
## it should include …

- [x] review a number of the overviews of 10x that have already been written
- [x] look at what's on the demo site
- [x] pick or piece together the best one (1-2 sentences)

## it's done when …
- [ ] the team has agreed upon the content and there are no more comments/suggestions in the doc

**Comment by carodew** [comment]
This might be a good task for Shawnique to start with, depending on start date.

**Comment by thebestsophist** [comment]
Gonna tackle this one and have Shawnique concentrate on the user research+recruiting later on

**Comment by thebestsophist** [comment]
Core questions:
- [ ] What is 10x? (_pull from existing content_)
- [ ] What sort of pitches are you looking for?
- [ ] How do I pitch?
  - [ ] What are the steps? What makes a good pitch? (**Answered in “Pitch an Idea” section?**)
  - [ ] What is a good pitch? 
  - [ ] Can I pitch something right now? When is the next round of pitches open?
  - [ ] How often is the call for submissions open?

**Comment by carodew** [comment]
The how do I pitch has it's own section in the iA but we have not gone so far as to decide if that's a separate section/page of the website or included on the home page or a mix of things. But also keep in mind #40 (mostly to not duplicate work)

**Comment by thebestsophist** [comment]
Created a branch for this draft: https://github.com/GSA/10x/commit/586d4cbac00b6437dd6f1a289226d2dad40e752b

I think it is good enough to review and start prototyping the front page design and testing the content.
