### ISSUE TITLE
Onboard Shawnique

### ISSUE THREAD

**Issue by carodew** [GSA/10x#55]
## this should include …

- [x] Shawnique is added to the GitHub repo as a collaborator 
~~- [ ] she's able to get the local install up and running~~
- [x] able to access the [information architecture](https://gsa-tts.slack.com/archives/C97A2AX16/p1519329265000247) and [storyboarding roadmap](https://user-images.githubusercontent.com/10144074/36212763-d6998344-1172-11e8-94da-d61461650831.png)
- [x] invited to all the website team meetings 
- [x] update her on where the content is right now - @willcahoe 
- [x] walk her through the framing docs created so far  - @willcahoe 
- [x] add to Team Drive in Google Drive

## it's done when 
- [x] Shawnique agrees it's done

**Comment by carodew** [comment]
I added this onboarding ticket and copied everything from @thebestsophist 's – it might not all be relevant but it's a starting point. 

Should try to divvy this up.

**Comment by willcahoe** [comment]
@shawnique and I have agreed that this card is finished. Moving to done.

**Comment by carodew** [comment]
@willcahoe pro tip – if you close the issue it will automatically move it to the done column in the Kanban board. 

Closing it now.
