### ISSUE TITLE
Integrate DAP into website

### ISSUE THREAD

**Issue by carodew** [GSA/10x#69]
## it should include …
- [x] reach out to Tim Lowden

## it's done when …
- [x] the DAP code snippet is on demo (and maybe prod?)
- [x] we have a link to view the Google Analytics for our site saved somewhere convenient

**Comment by thisisdano** [comment]
It's on `demo` now, but still not _active_ since it's only set to run on the live production site.

**Comment by willcahoe** [comment]
https://gsa-tts.slack.com/files/U02TZU28U/FA1AT7B45/screen_shot_2018-04-04_at_12.56.03_pm.png

**Comment by willcahoe** [comment]
@carodew let me know if you want access to see the analytics of this site, for now I'll just request access for myself

**Comment by willcahoe** [comment]
ditto @nicopapafil @lanebecker

**Comment by willcahoe** [comment]
DAP user agreement and responsibilities: https://www.digitalgov.gov/services/dap/common-questions-about-dap-faq/#part-7

**Comment by carodew** [comment]
I already have access to all DAP data so I just would need to navigate to the right spot. Which on it's own is no small feat.
