### ISSUE TITLE
Site/page social media metadata

### ISSUE THREAD

**Issue by thisisdano** [GSA/10x#78]
- [x] Research what social media metadata should appear on each page of the site
- [x] Add that metadata in such a way that it appears automatically with minimal manual configuration

**Comment by thebestsophist** [comment]
Optimal sizes:
- [Facebook link image](https://sproutsocial.com/insights/social-media-image-sizes-guide/#facebook): 1,200×627.
- [Twitter](https://sproutsocial.com/insights/social-media-image-sizes-guide/#twitter): 1024×512.

`  
    <meta property="og:title" content="[Title]" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="[1200x627].jpg" />
    <meta property="og:url" content="[url]" />
    <meta property="og:description" content="[description]" />

    
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:image" content="[1024x512].jpg" />`

**Comment by thisisdano** [comment]
Added as of https://github.com/GSA/10x/commit/72a011428c8d7e69807753e755e48a3b8f5e95dd
PR to follow
