### ISSUE TITLE
Updated IA map and per-section voice/tone/content prompts

### ISSUE THREAD

**Issue by thebestsophist** [GSA/10x#80]

**Comment by willcahoe** [comment]
@RyanSibley my assumption is that any tasks that were previously assigned to Cordelia should be moved to you. Let me know if this card is no longer relevant, or if it is not something you are prepared to take on at the moment.

**Comment by thebestsophist** [comment]
Ack, I think I (mostly) finished this! https://app.mural.ly/t/gsa6/m/gsa6/1521212827619/4f2b54cf4c07e2004577a34ed123fc3ddf2c7d16
