### ISSUE TITLE
Adding DAP script

### ISSUE THREAD

**Issue by tdlowden** [GSA/10x#82]
by request of @willcahoe,  I'd like to get the DAP script added. I think I can try to issue a PR for it myself, my question is this:

would you rather I create a new include {% dap_script.html %} or add it into the google-analytics.html file?

**Comment by willcahoe** [comment]
Thanks, Tim! I will check with the team and get back to you today on your question

**Comment by thisisdano** [comment]
@tlowden let's add it as a separate include — thank you!

**Comment by tdlowden** [comment]
Awesome, tried it here. https://github.com/GSA/10x/pull/83

I'm no jekyll pro, so please give it a good look. Thanks!
