### ISSUE TITLE
Build the Footer

### ISSUE THREAD

**Issue by willcahoe** [GSA/10x#88]
## it should include …

- [x] Privacy Policy
- [ ] FOIA
- [ ] Budget and Performance Reports
- [ ] Usa.gov
- [ ] Organizational Information
- [ ] Cross agency portals?
- [x] No Fear Act
- [x] contact info – 10x@gsa.gov 

## it's done when …
- [ ] We've had someone from the Digital Gov Team look at the footer and give it their blessing

**Comment by willcahoe** [comment]
Source: https://www.digitalgov.gov/resources/required-web-content-and-links/

@thisisdano I don't expect you to have the budget information or organization information handy, I can help you get those things when we cross this bridge.

**Comment by willcahoe** [comment]
[DAP and Privacy Policy.pdf](https://github.com/GSA/10x/files/1908784/DAP.and.Privacy.Policy.pdf)

**Comment by carodew** [comment]
Also – via GSA's web policy, needs to have some way to contact 10x ... so 

an email

or something.

**Comment by carodew** [comment]
https://www.gsa.gov/reference/freedom-of-information-act-foia – FOIA link, and that's the only thing missing

**Comment by carodew** [comment]
I'm calling this done for now.
