### ISSUE TITLE
Decide where page updates will live

### ISSUE THREAD

**Issue by willcahoe** [GSA/10x#90]
Part of the functionality of our website will involve communicating 10x updates:

- Which phase we are in (accepting pitches, announcing awards, etc.)
- List of anonymized pitches, both accepted and not accepted for funding
- Miscellaneous updates, success stories, project report-outs, etc.

Steps:

- [ ] Options have been identified 
- [ ] Content and design considerations have been identified

It's done when...

- [ ] The team reaches consensus

**Comment by RyanSibley** [comment]
I'm working on the landing page nav and have a placeholder for `updates`.  We should start working on actual content for this page, even if it's just placeholder. 

https://docs.google.com/document/d/1U5_XRZpVZOuWiGVTNDu9Siw84s3r4Vh1ZSxX5acKEDc/edit#

**Comment by RyanSibley** [comment]
When we're ready, we can start the content on this page: https://docs.google.com/document/d/1fhXa9DT_TAtmVFhFub-8R69o9VtmXhrQOHNEzFQfBCY/edit

also @thisisdano designed spaced for an `updates` section in the nav but it won't appear until we have a need/content for the page.
